import "server-only";
import { createSupabasePublicClient } from "@/lib/supabase/public";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export type BlogPost={id:string;title:string;slug:string;status:"draft"|"published"|"scheduled";excerpt:string|null;content:string;seo_title:string|null;seo_description:string|null;featured_image_url:string|null;category:string|null;topic_cluster:string|null;related_slugs:string[];author:string|null;published_at:string|null;scheduled_at:string|null;created_at:string;updated_at:string};
const fields="id,title,slug,status,excerpt,content,seo_title,seo_description,featured_image_url,category,topic_cluster,related_slugs,author,published_at,scheduled_at,created_at,updated_at";
export async function getPublishedPosts(){const db=createSupabasePublicClient();if(!db)return [];const{data}=await db.from("blog_posts").select(fields).eq("status","published").not("published_at","is",null).lte("published_at",new Date().toISOString()).order("published_at",{ascending:false});return(data??[]) as BlogPost[];}
export async function getPublishedPost(slug:string){const db=createSupabasePublicClient();if(!db)return null;const{data}=await db.from("blog_posts").select(fields).eq("slug",slug).eq("status","published").not("published_at","is",null).lte("published_at",new Date().toISOString()).maybeSingle();return(data as BlogPost|null)??null;}
export async function getAdminPosts(){const db=await createSupabaseServerClient();if(!db)return [];const{data}=await db.from("blog_posts").select(fields).order("updated_at",{ascending:false});return(data??[]) as BlogPost[];}
export async function getAdminPost(id:string){const db=await createSupabaseServerClient();if(!db)return null;const{data}=await db.from("blog_posts").select(fields).eq("id",id).maybeSingle();return(data as BlogPost|null)??null;}
