import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
function clean(value:unknown){return typeof value==="string"?value.trim():null;}
async function admin(){const db=await createSupabaseServerClient();if(!db)return null;const{data:{user}}=await db.auth.getUser();if(!user)return null;const{data}=await db.from("admin_users").select("id").eq("id",user.id).maybeSingle();return data?db:null;}
function postBody(body:any){const status=body.status==="published"||body.status==="scheduled"?body.status:"draft";return{title:clean(body.title)||"Untitled article",slug:(clean(body.slug)||"untitled-article").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,120),status,excerpt:clean(body.excerpt),content:typeof body.content==="string"?body.content:"",seo_title:clean(body.seo_title),seo_description:clean(body.seo_description),featured_image_url:clean(body.featured_image_url),category:clean(body.category),topic_cluster:clean(body.topic_cluster),related_slugs:Array.isArray(body.related_slugs)?body.related_slugs.filter((v:any)=>typeof v==="string").slice(0,20):[],author:clean(body.author),published_at:status==="published"?(clean(body.published_at)||new Date().toISOString()):null,scheduled_at:status==="scheduled"?clean(body.scheduled_at):null,updated_at:new Date().toISOString()};}
export async function POST(request:Request){const db=await admin();if(!db)return NextResponse.json({error:"Unauthorized."},{status:401});const body=await request.json().catch(()=>null);if(!body)return NextResponse.json({error:"Invalid request."},{status:400});const{data,error}=await db.from("blog_posts").insert(postBody(body)).select("id").single();if(error)return NextResponse.json({error:error.message},{status:400});revalidatePath("/blog");return NextResponse.json({id:data.id});}
export async function PATCH(request:Request){const db=await admin();if(!db)return NextResponse.json({error:"Unauthorized."},{status:401});const body=await request.json().catch(()=>null);if(!body?.id)return NextResponse.json({error:"Article id is required."},{status:400});const{error}=await db.from("blog_posts").update(postBody(body)).eq("id",body.id);if(error)return NextResponse.json({error:error.message},{status:400});revalidatePath("/blog");if(body.slug)revalidatePath(`/blog/${body.slug}`);return NextResponse.json({ok:true});}
export async function DELETE(request:Request){const db=await admin();if(!db)return NextResponse.json({error:"Unauthorized."},{status:401});const body=await request.json().catch(()=>null);if(!body?.id)return NextResponse.json({error:"Article id is required."},{status:400});const{error}=await db.from("blog_posts").delete().eq("id",body.id);if(error)return NextResponse.json({error:error.message},{status:400});revalidatePath("/blog");return NextResponse.json({ok:true});}
