import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getPublishedPost } from "@/lib/blog/posts";
import { renderBlogContent, RelatedLinks } from "@/lib/blog/render";
import { JsonLd } from "@/components/seo/JsonLd";
export async function generateMetadata({params}:{params:{slug:string}}):Promise<Metadata>{const post=await getPublishedPost(params.slug);if(!post)return{};return{title:post.seo_title||post.title,description:post.seo_description||post.excerpt||undefined,alternates:{canonical:`/blog/${post.slug}`}};}
export default async function BlogArticle({params}:{params:{slug:string}}){const post=await getPublishedPost(params.slug);if(!post)notFound();return <article className="container-page max-w-3xl py-14 md:py-20">
<JsonLd data={{"@context":"https://schema.org","@type":"Article","headline":post.title,"description":post.seo_description||post.excerpt||undefined,"datePublished":post.published_at||undefined,"dateModified":post.updated_at||undefined,"author":post.author?{"@type":"Person","name":post.author}:{"@type":"Organization","name":"OnlyPDF"},"mainEntityOfPage":{"@type":"WebPage","@id":`https://onlypdf.online/blog/${post.slug}`}}} /><p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">{post.category||"PDF guide"}</p><h1 className="mt-3 text-3xl sm:text-5xl">{post.title}</h1>{post.excerpt&&<p className="mt-5 text-lg leading-8 text-ink-muted">{post.excerpt}</p>}<div className="mt-8 flex gap-3 text-xs text-ink-soft">{post.author&&<span>By {post.author}</span>}{post.published_at&&<span>{new Date(post.published_at).toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"})}</span>}</div>{post.featured_image_url&&<div className="mt-8">
<img src={post.featured_image_url} alt={post.title} className="w-full rounded-card border border-border object-cover" />
{post.image_photographer&&post.image_provider&&<p className="mt-2 text-xs text-ink-soft">Photo by {post.image_photographer} on {post.image_provider}{post.image_source_url&&<> · <a href={post.image_source_url} target="_blank" rel="noreferrer" className="underline">Source</a></>}</p>}
</div>}<div className="mt-10 space-y-5">{renderBlogContent(post.content)}</div><RelatedLinks slugs={post.related_slugs||[]} /></article>}
